### ISSUE TITLE
Permissions for /var directory

### ISSUE THREAD

**Issue by jcassoumounat** [KAIST-IS521/TeamFour#19]
I encounter a problem due to the permission that is needed to change the /var directory. I can update flag file only with sudo command. Do you know if there is other options (in order to skip the sudo command) ?

**Comment by oxsignal** [comment]
You can simply  change  the  permission of the  directory  via 'chmod' command.

**Comment by jcassoumounat** [comment]
If I do it inside my program, it tells me that the chmod command isn't permitted for /var.

**Comment by jcassoumounat** [comment]
if( chmod( "/var", S_IRUSR | S_IWUSR ) == -1 ) {
    perror( "/var" );
}

**Comment by jcassoumounat** [comment]
Or I could do it in the terminal but I still need the sudo command

**Comment by oxsignal** [comment]
I think  your service  account should  modify  the write permission of /var using sudo command  before  launch  your  service.

**Comment by oxsignal** [comment]
There is  no option to write something in the directory without changing permission.

**Comment by jcassoumounat** [comment]
Ok thanks, I will do that then !

**Comment by oxsignal** [comment]
We encountered same problem because we also use /var/log. 

You guys have three options:

1. Add your account in syslog group. (Modify /etc/group)
2. Use `sudo`
3. Change the permission of the /var/log/. (Use `chown`)

(4). We also use `chmod` but not recommended.

**Comment by SeungwonWoo** [comment]
I will close this issue.
