### ISSUE TITLE
[Notary][Launcher] JSON format between notary and launcher

### ISSUE THREAD

**Issue by jaemoon-sim** [KAIST-IS521/TeamFour#23]

**Comment by jaemoon-sim** [comment]
Notary -> Launcher
{ 
   “name” : FILE_NAME, 
   “body”  : FILE_CONTENT (plain text),
   “sign”   : sign(timestamp || FILE_NAME || FILE_CONTENT)
}

**Comment by SeungwonWoo** [comment]
We will use JSON format in description
