### ISSUE TITLE
[Notary][Launcher] Verify each other 

### ISSUE THREAD

**Issue by jaemoon-sim** [KAIST-IS521/TeamFour#24]
Please leave comments how we can solve this problem

**Comment by oxsignal** [comment]
We can use notary's key. The file send by notary is already signed by Notary.

**Comment by jaemoon-sim** [comment]
Oh.. I've been writing down exact same scheme 👍

**Comment by jaemoon-sim** [comment]
Private Key : Notary server has it
Public Key  : Upload it to MIT PGP Key server (for project 'Government' & for verification)

**Comment by oxsignal** [comment]
We will use our own private key.
I will close the issue.
