### ISSUE TITLE
[Notice] About launcher program

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/TeamFour#28]
I just discussed about communication with one of member in Government.

In notary service, we don't have to send the received file to the launcher as Launcher and Notary is independent program.

Government will send only text-based file.
Our Job is just verifying the file (Might be Government's key) and signed it with our key.
After then, we send signed file to the client.

so in launcher's side, it doesn't care about output at the moment.

**Comment by jaemoon-sim** [comment]
👍

**Comment by SeungwonWoo** [comment]
OK, I will close this issue.
