### ISSUE TITLE
[NOTICE] Notary public key published

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/TeamFour#29]
I attached our Notary key below:

http://pgp.mit.edu/pks/lookup?search=IS521_notary&op=index

Also, you may lookup our pulbic key by searching:
ID : IS521_notary
E-mail : IS521_notary@kaist.ac.kr (This is not a real mail, please don't send any mail to this address)

**Comment by SeungwonWoo** [comment]
Thank You !!

**Comment by oxsignal** [comment]
If anyone needs my private key for test purpose, please let me know.

**Comment by oxsignal** [comment]
Everyone has our public key. I closed the issue.
