### ISSUE TITLE
Fix code related to 'gpg' variable global problem

### ISSUE THREAD

**Issue by juanaevv** [KAIST-IS521/TeamFour#31]
I pushed notary program, which can get file from test client.
But 'import_keys' function and 'send_file_with_sign' function has global variable problem related to 'gpg'

Below is test client code
------------------------------------------------------------------------------------------------------------------

import socket
import sys

s= socket.socket()
port = 8000

s.connect(("127.0.0.1",port))
f=open(sys.argv[1],'rt')
print 'sending...'
l = f.read(1024)
while(l):
        print 'Sending..'
        s.send(l)
        l = f.read(1024)
f.close()
print 'Done sending'
s.close()

**Comment by oxsignal** [comment]
Solved
