### ISSUE TITLE
[Notary Program]Log issue

### ISSUE THREAD

**Issue by juanaevv** [KAIST-IS521/TeamFour#33]
I corrected log problem.
If you want to log some comments, just using logging.exception, logging.info or logging.debug method. Each has different level. And I also make it possible to record all levels of logging message.

Also, you must make log file (/var/log/notary/test.log) in advance using shell command. This program does not create log file.

**Comment by oxsignal** [comment]
For testing purpose, I added a log function to leave error log to a console.
