### ISSUE TITLE
Some problems in verifying the signature...

### ISSUE THREAD

**Issue by jcassoumounat** [KAIST-IS521/TeamFour#34]
I'm getting stuck since few days in the verifying of the signature ...
"We generate the signature as follows. We first concatenate the GitHub ID of the signer with a colon ':' and the new flag. Thus, we get the following string: GitHubID:1234567890ABCDEF. Next we sign the
concatenated string with the signer's private key. Finally, we base64-encode the signature."
I need to verify this signature but I don't know how to proceed in a simple way... I have the signature in a buffer. 
If someone has an idea...

**Comment by SeungwonWoo** [comment]
I already tried to verify a signature in C. I got to know there is gpgme to support the gpg functions. But, that was complicated. So, Jaemoon will write a code using gpg's command in shell what we learned. I don't know it is successful. That's a simple way than using gpgme, But I worried about that is like trick..

**Comment by jaemoon-sim** [comment]
Actually Notary program already has some code to verify signature using python2.7

As Sengwon mentioned, I am using part of Notary program to verify signatures.

**Comment by oxsignal** [comment]
Please refer 'notary-program' repository
somewhat encoding is easy-task.

**Comment by jcassoumounat** [comment]
Yes I have seen about gpgme but too complicated for me...
Ok I will check that, thank you :)

**Comment by SeungwonWoo** [comment]
I will close this issue.
