### ISSUE TITLE
[NOTARY PROGRAM] Authentication

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/TeamFour#36]
I think  we are not supposed to authenticate our client.

Unfortunately, we have to authenticate user  before  getting  file. As the instruction specifies protocol, we also have to make a designated client :/

**Comment by juanaevv** [comment]
I finished Authentication part. Also, I uploaded client1.py for Authentication function
Usage is described in NOTARY.md

**Comment by juanaevv** [comment]
Also, I make new gpg object in Authentication function to check whether github ID, which comes from client, is valid or not, and simplify finding corresponding key
