### ISSUE TITLE
[Flag-Updater] About decryption of GPG TA's private signature

### ISSUE THREAD

**Issue by jcassoumounat** [KAIST-IS521/TeamFour#37]
I tried what we were talking about Gunwoo (hoping that I didn't made a big failure on the name :p ) and it doesn't work to decrypt a file (signed with a private key) with a public key...

**Comment by SeungwonWoo** [comment]
Did you try the decryption in command line?

**Comment by jcassoumounat** [comment]
Yes I did... And it doesn't work too... Even if I encrypt with a public key, I can not decrypt with a public key...

**Comment by jcassoumounat** [comment]
I have actually the same problem to decode with our team key (because in this case I should put our private key on github :/ )

**Comment by jcassoumounat** [comment]
I tried my program with only my key (which is quite useless here) and it works. Meaning that I just have to find the command to do this and it will be over...

**Comment by SeungwonWoo** [comment]
I have actually the same problem to decode with our team key (because in this case I should put our private key on github :/ )

==> Did you check the private key's list? If the private key is in the list, I don't know how to process the situation.

**Comment by SeungwonWoo** [comment]
In tonight, I will talk about the problem with several team members.

**Comment by SeungwonWoo** [comment]
I recommend you to reboot your VM. If it does not work, you reinstall your VM..... Maybe it will work..

**Comment by jcassoumounat** [comment]
Ok so know the private key is in the list so I just need the passphrase (if you can send it to me). But actually, the computer that will run the flag updater won't have our private key in the list ? Isn't it ?

**Comment by oxsignal** [comment]
Nope. Flag updater will have our private key

**Comment by jcassoumounat** [comment]
Ok so this is a problem solved.
Now it just remains the problem with TA's encrypted message....

**Comment by SeungwonWoo** [comment]
You should ask TA that issue.
