### ISSUE TITLE
[Notice] Remain to do

### ISSUE THREAD

**Issue by SeungwonWoo** [KAIST-IS521/TeamFour#38]
- [x] Flag Updater
- [x] SLA
- [x] Authentication (in notary program)
- [x] README.md
- [x] Makefile
- [x] Merge branch

Anything else?

**Comment by SeungwonWoo** [comment]
I check 'authentication' part. It is complete.

**Comment by oxsignal** [comment]
I think SLA checker and Flag updater are urgent ones. We already make our client program but it is written in Python, not in C.

**Comment by oxsignal** [comment]
Maybe we should verify all of our protocol in vagrant VM. My test environment is not quite stable;
Also in our program, we should specify build dependencies. I will update for this

**Comment by SeungwonWoo** [comment]
It is clear.
