### ISSUE TITLE
Issues on build script

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/TeamFour#45]
Hi, this is TA examining your team project. Please solve the following issue.

- Please add the following line to `install.sh` script, which is needed when we tested your build script in pure debian image.

`sudo apt-get install libgpgme11-dev`

- add `-y` option to `apt-get install` commands, so the package install can proceed without an interaction with user.

Thank you.

**Comment by SeungwonWoo** [comment]
We forgot it. Thanks and Sorry.
I updated this issue. So, I'll close.
